config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  get "bienvenida", to:"home#index"
  get "perfil", to:"users#edit"
  root to:"home#index" #ruta base

  # get "articles/user/:user_id", to:"articles#from_author"

  resources :users, only: [:update]
  resources :articles do 
      get "user/:user_id", to:"articles#from_author", on: :collection
  end
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get "articles", to:"articles#index"
  # get "articles/new", to:"articles#new", as: :new_articles
  # get "articles/:id", to:"articles#show"
  # get "articles/:id/edit", to:"articles#edit"
  # patch "/articles/:id", to:"articles#update", as: :article #EDIT
  # post "articles", to:"articles#create" #SEND
  # delete "articles/:id", to: "articles#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text:content
  belongs_to :user #campo adicional
  has_many :has_categories
  has_many :categories, through: :has_categories
  attr_accessor :category_elements

def save_categories
  # category_elements 1,2,3
  # Convertir eso en un arregle 1,2,3 => [1,2,3]
  #=====> categories_array = category_elements.split(",") <=====
  #Iterar ese arreglo
  return has_categories.destroy_all if category_elements.nil? || category_elements.empty?
  category_elements.each do |category_id|

    #Unless es la inverso del if => "A menos que"
    #unless HasCategory where(article:self, category_id:category_id).any?
    #Si da verdadero no se crea


      HasCategory.find_or_create_by(article: self, category_id: category_id)
  #find_or_create para evitar duplicados
  end
end


end

app/models/category.rb
class Category < ApplicationRecord
  has_many :has_categories
  has_many :articles, through: :has_categories
end

app/models/has_category.rb
class HasCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

#before_action :find_article, only:[:show,:edit,:destroy,:update]
before_action :find_article, except:[:new, :create,:index, :from_author]
before_action :authenticate_user!, only: [:new, :create, :update, :destory]
def index
  @articles=Article.all
end
  def show
    
  end

   def edit
    @categories = Category.all
   end

   def update
    @article.update(article_params)
    @article.save_categories
    redirect_to @article
   end

  def new
    @article=Article.new
    @categories = Category.all
  end

  def create
   @article = current_user.articles.create(article_params)
   @article.save_categories
   redirect_to @article
  end

  def destroy
    
    @article.destroy
    redirect_to root_path
  end
  
  def find_article
    @article=Article.find(params[:id])
  end

  def from_author
    @user = User.find(params[:user_id])
  end

  def article_params
    params.require(:article).permit(:title, :content, category_elements: [])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title, :color)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def edit
  end
  def update
    current_user.update(user_params)
    
    redirect_back(fallback_location: root_path)
  end
  def user_params
    params.require(:user).permit(:avatar, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fa_icon_tag(name, opts={})
		content_tag(:i, nil, class: "fa fa-#{name} #{opts[:class]}")
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_article.html.erb
<div class="card padding margin-top">
    <h3 class="text-uppercase"><%= article.title %></h3>
    <p class="text-secondary"><%= article.created_at %></p>
    <%= link_to "Ver mas", article %>
</div>

    <br/>

app/views/articles/_comments.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <h4 class="modal-title" id="myModalLabel">Modal title</h4>
</div>
<div class="modal-body">
  *Modal content comes here*
</div>
<div class="modal-footer">
  <button class="btn btn-primary">Save</button>
</div>

app/views/articles/_form.html.erb
<%= form_with(model:@article, local:true) do |form| %>
<div style="padding-top:40px;">
  <div class="field">
  <p><strong><%=form.label :título %></strong></p>
  <%= form.text_field :title %><p>
  </div>
  <div class="field">
    <p><strong><%= form.label :Categorías%></strong></p>
    <div class="row">
    <% @categories.each do |category| %>
      <label class="col-6 col-sm-4">
      <%= form.check_box :category_elements, {multiple: true}, category.id, nil %>
      <%= category.title%>
      </label>
      <% end %>
    </div>
    <%# 1,2 %>
  </div>
  <br>
  <div class="field">
  <p><strong><%=form.label :contenido %></strong></p>
  <%= form.rich_text_area :content %>
  </div>
  <br/>
  <div>
  <%= form.submit "Crear Artículo", class:"btn btn-success"%>
  </div>
  </div>
<%end%>

app/views/articles/edit.html.erb
<div class="color-fondo">
<div  style="padding:10%">
<div class="small-container center-block">
<h1>Editar Artículo</h1>
<%= form_with(model:@article, local:true) do |form| %>
<div style="padding-top:40px;">
  <div class="field">
  <p><strong><%=form.label :título %></strong></p>
  <%= form.text_field :title %><p>
  </div>
  <div class="field">
    <p><strong><%= form.label :Categorías%></strong></p>
    <div class="row">
    <% @categories.each do |category| %>
      <label class="col-6 col-sm-4">
      <%= form.check_box :category_elements, {multiple: true}, category.id, nil %>
      <%= category.title%>
      </label>
      <% end %>
    </div>
    <%# 1,2 %>
  </div>
  <br>
  <div class="field">
  <p><strong><%=form.label :contenido %></strong></p>
  <%= form.rich_text_area :content %>
  </div>
  <br/>
  <div>
  <%= form.submit "Editar Artículo", class:"btn btn-success"%>
  </div>
  </div>
<%end%>
</div>
</div>
</div>

app/views/articles/from_author.html.erb
<div class="large-container center-block">
  <h1>Articulos publicados por <%= @user.name %></h1>
  <%= render @user.articles%>
</div>

app/views/articles/index.html.erb
<div class="color-fondo">
<div class="large-container center-block">
<br/>
  <h1>Mis Articulos</h1>
  <br/>
  <%= render @articles%>
</div>
</div>

app/views/articles/new.html.erb
<div class="color-fondo">
<div  style="padding:10%">
<h1>Nuevo Artículo</h1>
<%= render "articles/form" %>
</div>
</div>

app/views/articles/show.html.erb
<div class="large-container center-block">
<br>
  <h1><%= @article.title%></h1>
  <div>
    <p>Escrito por:<strong> <%= @article.user.name %></strong></p>
  </div>
  <div>
  <%= @article.content%>
  </div>
  <br>
  <div class="margin-top">
  <p class="label"><strong>Tags</strong></p>
  <p><% @article.categories.each do |category| %>
    <span class="badge badge-pill padding" style="background-color:<%= category.color %>; border-radius: 50px">
      <%= link_to category.title, category, class:"text-white" %>
    </span>
  <% end %></p>
  </div>
  <br/>
  <div>
  <%=link_to "Eliminar", @article, method: :delete, class:"btn btn-danger"%>
  <%=link_to "Editar" , edit_article_path, class:"btn btn-warning"%>
  
  </div>
</div>

app/views/categories/_form.html.erb
<div class="large-container center-block">
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="field">
    <p><%= form.label :título %></p>
    <p><%= form.text_field :title %></p>
  </div>
  <div class="field">
    <p><%= form.label :color %></p>
    <%= form.color_field :color %>
  </div>
<br>
<br>
  <div class="actions">
    <%= form.submit "Guardar", class:"btn btn-success"%>
    <%= link_to 'Regresar', categories_path, class:'btn btn-secondary'%>
  </div>
<% end %>
</div>

app/views/categories/edit.html.erb
<div class="color-fondo">
<div class="small-container center-block">
<div  style="padding:10%">
<br>
<br>
<br>
<br>
<br>
<br>
  <h1>Editar Categoría</h1>

  <%= render 'form', category: @category %>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</div>
</div>
</div>

app/views/categories/index.html.erb
<div class="color-fondo">
<div class="">
<div  style="padding:10%">
<p id="notice"><%= notice %></p>

<h1>Categorías</h1>
  <br>
    <table class="table">
      <thead>
        <tr>
          <th>Título</th>
          <th>Color</th>
          <th colspan="3">Acciones</th>
        </tr>
      </thead>

      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.title %></td>
            <td><%= category.color %></td>
            <td><%= link_to 'Mostrar', category , class:"btn btn-warning"%></td>
            <td><%= link_to 'Editar', edit_category_path(category), class:"btn btn-info" %></td>
            <td><%= link_to 'Eliminar', category, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-danger"%></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <br>

<%= link_to 'Nueva Categoría', new_category_path , class:"btn btn-success"%>
<br>
<br>
<br>
<br>
<br>
<br>
</div>
</div>
</div>

app/views/categories/new.html.erb
<div class="small-container center-block" >
<br>
  <h1>Nueva Categoría</h1>

  <%= render 'form', category: @category %>

  
</div>

app/views/categories/show.html.erb
<div class="color-fondo">
<div class="large-container center-block">
<br/>
  <h1>Articulos publicados para <%= @category.title %></h1>
   <br/>
  <%= render @category.articles%>
</div>
</div>

app/views/home/index.html.erb
<div style="padding:20px">
<h3>Bienvenid@, <%= current_user.name %></h3>
<div style="align-items:center">
<%= image_tag("op2.jpeg", :alt => "rss feed", class:'mx-auto d-block') %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tu opinión</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'Tu_opinion.svg' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if notice %>
    <p class="alert alert-primary"><%= notice %></p>
  <%end %>
  <%if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <%end %>
  <%= render "partials/nav"%>
    <%= yield %>
  </body>
</html>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-expand-lg" style="background-color: #FFB833;">
<div class="container-fluid">
  <a class="navbar-brand" href="#">
    <%= image_tag("Tu_opinion.svg", :alt => "rss feed", height:30, width:30) %>
  </a>
      <div class="collapse navbar-collapse" id="navbarContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "Inicio", root_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "Articulos", articles_path, class:"nav-link"%>
            </li>
        
      <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "Escribir", new_article_path, class:"nav-link"%>
              </li>
              <li class="nav-item">
                <%= link_to "Categorías", categories_path, class:"nav-link"%>
              </li>
              <li class="nav-item">
                <%= link_to "Mi perfil", perfil_path, class:"nav-link"%>
              </li>
              
         </ul>
         <ul class="navbar-nav">
         <%if current_user.avatar.persisted? %>
              <li class="nav-item">
                <%= image_tag url_for(current_user.avatar),class:"rounded-circle", height:40, width:40 %>
              </li>
          <%end %>
                <li class="nav-item">
                <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class:"nav-link"%>
              </li>
        </ul>
      <% else %>
            <li class="nav-item">
              <%= link_to "Iniciar Sesión", new_user_session_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "Registrarse", new_user_registration_path, class:"nav-link"%>
            </li>
<%end %>
</div>
</div>
</nav>

app/views/users/edit.html.erb
<div class="color-fondo">
  <div class="small-container center-block">
  <div  style="padding:10%">
    <p class="font-weight-bold text-uppercase margin-top"><h1>Perfil</h1></p>
    <br>
    <div  style="text-align: center;">
    <% if current_user.avatar.attached? %>
      <%= image_tag url_for(current_user.avatar),class:"rounded-circle", height:200, width:200 %>
    <% end %>
    </div>
    <br>
    <%= form_with(model:current_user, local:true) do |form| %>
      <div class="field" >
        <p><%= form.label :avatar %></p>
        <p><%= form.file_field :avatar %></p>
        <p><%= form.label :correo_electrónico%></p>
        <p><%= current_user.email %></p>
        <p><%= form.label :nombre%></p>
        <p><%= form.text_field :name %></p>
      </div>
      <br>
      
        <%= form.submit "Guardar", class:"btn btn-success"%>
      
    <% end %>
    </div>
</div>
</div>